### ISSUE TITLE
Short question

### ISSUE THREAD

**Issue by marius-balteanu** [dickerpulli/job-dsl-promotions-plugin#1]
Hi @dickerpulli,

Is this plugin ready to use togheter with the Jenkins DSL plugin to generate promotions?

Thanks,
Marius

**Comment by dickerpulli** [comment]
No, sorry. I wait for Job DSL Plugin to develop its extension point.

**Comment by marius-balteanu** [comment]
Ok, thanks. Let me know if I can help you now since the extension point was released.

**Comment by pupssman** [comment]
What about https://github.com/codecentric/job-dsl-promotions-plugin ?

**Comment by dickerpulli** [comment]
Use the new fork!
